export const GET_ALL_CATEGORY = "Get_All_Category";
export const CREATE_CATEGORY = "CREATE_CATEGORY";

export const GET_ERROR = "Get_Error";

export const GET_ALL_BRAND = "Get_All_BRAND";
export const CREATE_BRAND = "CREATE_BRAND";

export const CREATE_SUB_CATEGORY = "CREATE_SUB_CATEGORY";

export const GET_SUB_CATEGORY = "GET_SUB_CATEGORY";

export const CREATE_PRODUCT = "CREATE_PRODUCT";

export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";

export const GET_SPECIFIC_PRODUCTS = "GET_SPECIFIC_PRODUCTS";

export const GET_ONE_CATEGORY = "GET_ONE_CATEGORY";

export const GET_ONE_BRAND = "GET_ONE_BRAND";

export const GET_SAME_PRODUCTS = "GET_SAME_PRODUCTS";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const CREATE_NEW_USER
= "CREATE_NEW_USER";
export const LOGIN_USER= "LOGIN_USER";
export const GET_CURRENT_USER="GET_CURRENT_USER";
export const FORGET_PASSWORD
="GET_CURRENT_USER";